import * as E from './engine.js';import {HttpGoProvider,requestFor} from './providers.js';
// Evaluations are a separate presentation layer. They never settle a timeline.
export function setupAI({staticHost=false,getGame,getSelected,isLAN,perform,onChange,message}){
 let provider=null,running=false,mode='human',humanColor='B',aiBusy=false,analyzing=false,lastSnapshot='',epoch=0;
 const estimates=new Map(),lineTrends=new Map(),globalTrend=[];
 const section=document.createElement('section');section.className='panel ai-panel';section.innerHTML=`<div class="section-head"><div><span class="eyebrow">OPTIONAL AI · 可选能力</span><h2>人类的选择，机器的参考</h2></div></div><div class="ai-controls"><label>对局模式 <select id="aiMode"><option value="human">双人同屏 / 局域网</option value="human-ai" disabled>人机（需接 AI）</option><option value="ai-ai" disabled>机机（需接 AI）</option></select></label><label>人类执 <select id="humanColor"><option value="B">黑</option><option value="W">白</option></select></label><input id="providerUrl" type="url" value="http://127.0.0.1:8787" aria-label="AI 服务地址"><button id="connectAI" class="ghost">连接 AI 服务</button><button id="startAI" disabled>开始 AI 落子</button><button id="analyzeAI" class="ghost" disabled>刷新分析</button></div><p id="aiStatus" class="muted">未连接 AI。可直接双人对弈；没有演示胜率或伪造数据</p><p class="muted">AI 首版策略：只推进自己可下的叶（按 ID 选择），不自动分叉或剪枝。人机 / 机机仅用于同屏模式。双方停一手后仍需人类确认死子与结果</p><div class="charts"><div><h3>当前时间线 · 黑方预测胜率</h3><p id="lineEstimate">暂无分析</p><svg id="lineChart" viewBox="0 0 440 110" role="img" aria-label="当前时间线预测趋势"></svg></div><div><h3>全局 · 黑方预计胜负权重</h3><p id="globalEstimate">暂无分析</p><svg id="globalChart" viewBox="0 0 440 110" role="img" aria-label="加权预测趋势"></svg></div></div><p class="muted">全局值 = Σ（叶权重 × 黑胜率），已结算叶用实际 1 / 0 / 0.5。它不是“整场获胜概率”，不会代替正式比分。趋势按分析完成的状态采样；陈旧或缺失分析不计算最新全局值</p>`;
 document.querySelector('.layout').after(section);const $=id=>document.getElementById(id);if(staticHost){$('providerUrl').value='';$('providerUrl').placeholder='你自己的 HTTPS AI provider 地址';$('aiStatus').textContent='静态版未连接 AI。可接自己配置的兼容 HTTPS provider（需正确 CORS）；本地 KataGo 请在本地 Node 页面连接。此站不托管 AI。';}const fingerprint=()=>E.exportGame(getGame());const key=(g,l)=>JSON.stringify({size:g.size,komi:E.effectiveKomi(g,l),history:l.history});
 const chart=(id,values)=>{const svg=$(id);svg.replaceChildren();const ns='http://www.w3.org/2000/svg';for(const y of [10,55,100]){const e=document.createElementNS(ns,'path');e.setAttribute('d',`M10 ${y}H430`);e.setAttribute('stroke','#344763');svg.append(e);}if(!values.length)return;const path=document.createElementNS(ns,'path');path.setAttribute('d',values.map((v,i)=>`${i?'L':'M'}${10+i*420/Math.max(1,values.length-1)} ${100-v*90}`).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#70ead2');path.setAttribute('stroke-width','2.5');svg.append(path);};
 function update(){const g=getGame(),l=E.lineById(g,getSelected()),estimate=estimates.get(l.id),fresh=estimate?.key===key(g,l);$('lineEstimate').textContent=l.status==='settled'?`实际结果：${l.result.winner==='B'?'黑胜':l.result.winner==='W'?'白胜':'平局'}`:estimate?`${(estimate.value*100).toFixed(1)}% · ${fresh?'当前历史节点':'陈旧分析，等待刷新'}`:'暂无分析';chart('lineChart',(lineTrends.get(l.id)||[]).map(p=>p.value));let total=E.fraction(0),missing=0;for(const line of g.lines){const e=estimates.get(line.id);const value=line.status==='settled'?(line.result.winner==='B'?1:line.result.winner==='W'?0:.5):e?.key===key(g,line)?e.value:null;if(value===null){missing++;continue;}total=E.add(total,E.fraction(BigInt(line.weight.n)*BigInt(Math.round(value*1e9)),BigInt(line.weight.d)*1000000000n));}const value=Number(BigInt(total.n)*1000000n/BigInt(total.d))/1000000;if(missing)$('globalEstimate').textContent=`等待 ${missing} 条时间线的当前分析`;else{$('globalEstimate').textContent=`${(value*100).toFixed(1)}% · 当前全局状态`;const state=fingerprint();if(globalTrend.at(-1)?.state!==state){globalTrend.push({state,value});if(globalTrend.length>120)globalTrend.shift();}}chart('globalChart',globalTrend.map(p=>p.value));$('startAI').textContent=running?'暂停 AI 落子':'开始 AI 落子';$('startAI').disabled=!provider||mode==='human'||isLAN();$('analyzeAI').disabled=!provider||analyzing;$('humanColor').disabled=mode!=='human-ai';}
 async function analyze(){if(!provider||analyzing)return;analyzing=true;const start=epoch,g=structuredClone(getGame()),state=E.exportGame(g);$('aiStatus').textContent='正在分析完整历史；新局面会使旧请求失效';update();try{for(const l of g.lines){if(start!==epoch||fingerprint()!==state)break;if(l.status==='settled')continue;const k=key(g,l);if(estimates.get(l.id)?.key===k)continue;const result=await provider.analyze(requestFor(g,l));if(start!==epoch||fingerprint()!==state)break;estimates.set(l.id,{key:k,value:result.blackWinrate});const trend=lineTrends.get(l.id)||[];trend.push({key:k,value:result.blackWinrate});if(trend.length>120)trend.shift();lineTrends.set(l.id,trend);update();}if(start===epoch&&fingerprint()===state){lastSnapshot=state;$('aiStatus').textContent='分析已更新 · 黑方视角 · 非正式比赛结果';}}catch(e){$('aiStatus').textContent='分析失败：'+e.message;lastSnapshot=state;}finally{analyzing=false;update();}}
 $('connectAI').onclick=async()=>{try{const endpoint=$('providerUrl').value.trim();if(!endpoint)throw new Error('请填写你自行配置的兼容 AI 服务地址');if(location.protocol==='https:'&&new URL(endpoint).protocol!=='https:')throw new Error('HTTPS 静态页面请使用兼容 HTTPS provider；本地 HTTP KataGo 请在本地 Node 页面连接，不要关闭浏览器安全检查');const candidate=new HttpGoProvider(endpoint),caps=await candidate.capabilities();if(caps.winratePerspective!=='black'||!caps.analyze||!caps.generateMove)throw new Error('服务需支持 analyze / generateMove，且明确 black 胜率视角');provider?.cancelAll();provider=candidate;epoch++;lastSnapshot='';for(const opt of $('aiMode').options)opt.disabled=false;$('aiStatus').textContent=`已连接 ${caps.name||'HTTP Go provider'}`;update();analyze();}catch(e){message('AI 连接失败：'+e.message,true);}};
 $('aiMode').onchange=()=>{mode=$('aiMode').value;running=false;onChange();update();};$('humanColor').onchange=()=>{humanColor=$('humanColor').value;onChange();};$('startAI').onclick=()=>{running=!running;update();};$('analyzeAI').onclick=()=>{lastSnapshot='';analyze();};
 const isAITurn=id=>{const g=getGame();if(!provider||mode==='human'||isLAN()||id===undefined||!E.canActOn(g,id))return false;return mode==='ai-ai'||E.replay(E.lineById(g,id).history,g.size).toPlay!==humanColor;};
 setInterval(async()=>{if(provider&&!analyzing&&fingerprint()!==lastSnapshot)analyze();if(!running||aiBusy)return;const target=E.eligibleIds(getGame()).find(id=>isAITurn(id));if(target===undefined)return;aiBusy=true;const g=structuredClone(getGame()),state=E.exportGame(g),l=E.lineById(g,target);try{const result=await provider.generateMove(requestFor(g,l));if(running&&fingerprint()===state&&isAITurn(l.id)){const applied=await perform({type:'play',id:l.id,index:l.history.length,at:result.move.type==='pass'?null:result.move.at});if(!applied){running=false;message('AI 返回了非法或重复落子，已暂停',true);}if(getGame().lines.some(l=>l.status==='scoring')){running=false;message('AI 已停下：有棋局进入计分，请双方检查死子并确认，或争议续弈');}}}catch(e){running=false;message('AI 落子暂停：'+e.message,true);}finally{aiBusy=false;update();}},1500);
 update();return {update,isAITurn,reset(){running=false;provider?.cancelAll();epoch++;estimates.clear();lineTrends.clear();globalTrend.length=0;lastSnapshot='';update();}};
}
