import * as E from './engine.js';
import {createTree} from './tree.js';
import {setupAI} from './ai.js';
import {STATIC_HOST} from './deployment.js';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let ai=null;
let game=E.createGame(),selected=1,index=0,pending=null,session=null,busy=false,polling=false,connecting=false,networkLost=false;
const treePanel=document.querySelector('.tree-panel'),overview=document.createElement('details');overview.className='overview';overview.open=matchMedia('(min-width:801px)').matches;const summary=document.createElement('summary');summary.textContent='时间线树 · 展开 / 收起';overview.append(summary,treePanel);document.querySelector('aside').insertBefore(overview,document.querySelector('aside').children[1]);
const confirmBar=document.createElement('div');confirmBar.className='actions';confirmBar.innerHTML='<button id="confirmMove">确认落子</button><button id="cancelMove" class="ghost">取消预览</button><span class="muted">先预览，再确认，避免误触</span>';document.querySelector('.history-row').before(confirmBar);
const tree=createTree($('tree'),(id,depth)=>{selected=id;index=depth;pending=null;render();});
function message(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function chosenLimit(){const v=$('branchLimit').value;return v==='none'?null:v==='custom'?Number($('customLimit').value):Number(v);}
function chosenC(){return $('compensationC').value==='custom'?$('customC').value.trim():$('compensationC').value;}
function chosenPruning(){const mode=$('pruningMode').value;return {pruningMode:mode,compensationC:mode==='komi'?chosenC():'32'};}
function updatePruningControls(){const active=$('pruningMode').value==='komi';$('compensationControls').hidden=!active;$('compensationHint').hidden=!active;$('customC').hidden=$('compensationC').value!=='custom';$('branchLimit').disabled=active;$('customLimit').disabled=active;if(active)try{const info=E.compensationInfo(chosenC()),percent=Number(info.actualMin.n)/Number(info.actualMin.d)*100,raw=Number(info.rawMinimumCompensation.n)/Number(info.rawMinimumCompensation.d),rounded=Number(info.roundedMinimumCompensation.n)/Number(info.roundedMinimumCompensation.d);$('compensationHint').textContent=`实际最低新生叶 ${E.weightText(info.actualMin)}（${Number(percent.toPrecision(7)).toString()}%）· 原始最小补偿 ${raw} 目 · 半目向上取整 ${rounded} 目；本模式不用手动门槛`;}catch(e){$('compensationHint').textContent=e.message;}}
function currentLine(){return E.lineById(game,selected);}
function canAct(){const l=currentLine();return !ai?.isAITurn(selected)&&E.canActOn(game,selected,session?.role);}
function stoneSymbol(color){const stone=document.createElement('span');stone.className='stone-symbol '+(color==='B'?'black':'white');stone.setAttribute('aria-hidden','true');return stone;}
function colorName(c){return c==='B'?'黑':'白';}
function element(tag,attrs){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function board(){const l=currentLine(),s=E.replay(l.history.slice(0,index),game.size),n=game.size,pad=27,gap=32,end=pad+(n-1)*gap,max=end+pad,svg=$('board');svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${max} ${max}`);svg.append(element('rect',{x:0,y:0,width:max,height:max,fill:'#d6b47d',rx:8}));
 for(let a=0;a<n;a++){const q=pad+a*gap;svg.append(element('path',{d:`M${pad},${q}H${end}M${q},${pad}V${end}`,stroke:'#765a35','stroke-width':.8}));const label=element('text',{x:q,y:16,'text-anchor':'middle',fill:'#745933','font-size':10});label.textContent='ABCDEFGHJKLMNOPQRST'[a];svg.append(label);const num=element('text',{x:11,y:q+3,'text-anchor':'middle',fill:'#745933','font-size':9});num.textContent=n-a;svg.append(num);}
 const stars=n===9?[2,4,6]:n===13?[3,6,9]:[3,9,15];for(const a of stars)for(const b of stars)svg.append(element('circle',{cx:pad+a*gap,cy:pad+b*gap,r:2.1,fill:'#765a35'}));
 for(let i=0;i<n*n;i++){const x=pad+i%n*gap,y=pad+Math.floor(i/n)*gap,c=s.board[i];if(c){svg.append(element('circle',{cx:x,cy:y,r:14,fill:c==='B'?'#18202b':'#fff8e9',stroke:c==='B'?'#070e19':'#c4b9a4','stroke-width':1.3}));if(index===l.history.length&&l.dead.includes(i))svg.append(element('path',{d:`M${x-7},${y-7}l14,14m0,-14l-14,14`,stroke:'#f25f76','stroke-width':3}));}if(pending===i)svg.append(element('circle',{cx:x,cy:y,r:13,fill:s.toPlay==='B'?'#18202b88':'#fff8e999',stroke:'#2d8994','stroke-width':3,'stroke-dasharray':'3 2'}));const last=l.history[index-1];if(last?.type==='play'&&last.at===i)svg.append(element('circle',{cx:x,cy:y,r:4,fill:c==='B'?'#70ead2':'#744dcc'}));const hit=element('rect',{x:x-16,y:y-16,width:32,height:32,class:'hit',tabindex:0,role:'gridcell','aria-label':`${'ABCDEFGHJKLMNOPQRST'[i%n]}${n-Math.floor(i/n)} ${c?colorName(c)+'子':'空'}`});const click=()=>{if(l.status==='scoring'&&index===l.history.length){act({type:'toggleDead',id:selected,at:i});return;}if(!canAct()){message(E.turnInfo(game,selected).waiting?E.turnInfo(game,selected).reason:'请选择你本轮尚未操作、且当前轮到你颜色的时间线',true);return;}try{E.apply(s,{type:'play',at:i,color:s.toPlay},n);pending=i;board();$('confirmMove').disabled=false;message(`预览 ${'ABCDEFGHJKLMNOPQRST'[i%n]}${n-Math.floor(i/n)}，点击“确认落子”提交`);}catch(e){message(e.message,true);}};hit.addEventListener('click',click);hit.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click();}});svg.append(hit);}
}
function render(){if(!game.lines.some(l=>l.id===selected))selected=game.lines[0].id;const l=currentLine();index=Math.min(index,l.history.length);$('size').value=game.size;$('komi').value=game.komi;$('pruningMode').value=game.pruningMode||'none';const c=game.compensationC||'32';$('compensationC').value=['8','32','256'].includes(c)?c:'custom';$('customC').value=c;updatePruningControls();const exp=game.branchLimitExponent;$('branchLimit').value=exp==null?'none':exp<=9?String(exp):'custom';$('customLimit').hidden=exp==null||exp<=9;if(exp>9)$('customLimit').value=exp;$('round').textContent=`● 黑第 ${game.turns.B.epoch} 轮 · 剩 ${game.turns.B.pending.length} 线　○ 白第 ${game.turns.W.epoch} 轮 · 剩 ${game.turns.W.pending.length} 线`;$('lineTitle').textContent=`时间线 #${selected} · 权重 ${E.weightText(l.weight)}`;const turn=E.turnInfo(game,selected);$('turn').classList.toggle('turn-waiting',turn.waiting);$('turn').textContent=l.status==='playing'?turn.reason:l.status==='scoring'?'双方计分':`${l.result.winner==='draw'?'平局':colorName(l.result.winner)+'胜'}`;if(turn.canPlay)$('turn').replaceChildren(stoneSymbol(turn.toPlay),document.createTextNode(' '+colorName(turn.toPlay)+'方可下'));
 $('history').max=l.history.length;$('history').value=index;$('historyLabel').textContent=`第 ${index} / ${l.history.length} 步${index<l.history.length?(E.canBranch(game,l)?' · 历史预览：不同落子将创建分支，旧线保留':' · 已到分叉门槛，仅可继续当前叶'):' · 最新局面'} · 门槛 ${game.pruningMode==='komi'?E.weightText(E.compensationInfo(game.compensationC).actualMin)+'（新生叶）':game.branchLimitExponent==null?'不限制':'1/'+String(2n**BigInt(game.branchLimitExponent))}`;$('confirmMove').disabled=pending===null||!canAct()||busy;$('pass').disabled=!canAct()||busy;$('prune').disabled=!canAct()||busy||game.pruningMode==='none'||index===0;$('prev').disabled=index===0;$('next').disabled=index===l.history.length;$('scoring').hidden=l.status!=='scoring'||index!==l.history.length;
 if(l.status==='scoring'){const sc=E.score(game,selected);$('scorePreview').textContent=`黑 ${sc.B} · 白 ${sc.W}（含当前贴目 ${E.effectiveKomi(game,l)}） · 已确认：${l.approvals.map(colorName).join('、')||'无'}`;for(const c of ['B','W'])$('approve'+c).disabled=l.approvals.includes(c)||!!(session&&session.role!==c)||busy;}
 const t=E.totals(game);$('totals').replaceChildren();for(const[k,label]of Object.entries({B:'黑胜权重',W:'白胜权重',draw:'平局权重',unsettled:'未结算权重'})){const d=document.createElement('div');d.className='stat';const b=document.createElement('strong');b.textContent=E.weightText(t[k]);const span=document.createElement('span');span.textContent=label;d.append(b,span);$('totals').append(d);}$('matchResult').textContent=E.majority(t.B)?'黑方已锁定胜利':E.majority(t.W)?'白方已锁定胜利':t.unsettled.n==='0'?'对局结束 · 整体平局':'无限可能，尚未定局';
 $('pruningLedger').textContent=`剪枝模式：${{none:'不剪枝',resign:'认输剪枝',komi:'贴目补偿'}[game.pruningMode||'none']} · 本盘白贴目 ${E.effectiveKomi(game,l)} · 累计调整 ${game.komiCompensation?E.weightText(game.komiCompensation):'0/1'} 目`;$('archives').replaceChildren();for(const entry of game.archives||[]){const p=document.createElement('p');p.className='muted';p.textContent=`第 ${entry.round} 轮 · ${colorName(entry.actor)}方 ${entry.mode==='resign'?'认输':'贴目补偿'}剪枝 · ${entry.lines.length} 叶 · 原权重 ${E.weightText(entry.subtreeWeight)} · 白贴目调整 ${E.weightText(entry.komiDelta)}`;$('archives').append(p);}$('archivePanel').hidden=!(game.archives||[]).length;
 $('lines').replaceChildren();const done=game.lines.filter(l=>l.status==='settled').length;const settled=E.add(E.add(t.B,t.W),t.draw);$('lineCount').textContent=`完成 ${done} / ${game.lines.length} · 已结算 ${Number(BigInt(settled.n)*10000n/BigInt(settled.d))/100}%`; for(const line of game.lines){const b=document.createElement('button');const availability=E.turnInfo(game,line.id);b.className='line-item'+(line.id===selected?' selected':'')+(availability.waiting?' turn-waiting':'');const left=document.createElement('span');left.textContent=`${selected===line.id?'▶ ':''}#${line.id} · ${E.weightText(line.weight)}`;const right=document.createElement('small');right.textContent=`${line.history.length} 步 · ${line.status==='settled'?(line.archived?'认输归档':'已结算'):line.status==='scoring'?'待计分':availability.reason}`;if(availability.canPlay){right.textContent=right.textContent.replace(/● |○ /,'');right.prepend(stoneSymbol(availability.toPlay),document.createTextNode(' '));}b.append(left,right);b.onclick=()=>{selected=line.id;index=line.history.length;pending=null;render();};$('lines').append(b);}
 $('connection').textContent=STATIC_HOST?'静态同屏版':session?`房间 ${session.code} · ${colorName(session.role)}方`:'同屏模式';$('new').disabled=!!session;$('load').disabled=!!session;$('host').disabled=STATIC_HOST||!!session;$('join').disabled=STATIC_HOST||!!session;$('leave').disabled=!session;board();tree.render(game);ai?.update();
}
function localAction(a){switch(a.type){case'play':return E.play(game,a.id,a.index,a.at);case'toggleDead':return E.toggleDead(game,a.id,a.at);case'approveScore':return E.approveScore(game,a.id,a.color);case'resume':return E.resume(game,a.id);case'prune':return E.prune(game,a.id,a.index,E.replay(E.lineById(game,a.id).history,game.size).toPlay);}}
async function request(path,body,auth=true){if(STATIC_HOST)throw new Error('这是静态同屏版；局域网对战请打开房主 Node 服务提供的页面');const response=await fetch(new URL(path.replace(/^\//,''),import.meta.url),{method:body===undefined?'GET':'POST',headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(auth&&session?{Authorization:'Bearer '+session.token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});let data;try{data=await response.json();}catch{throw new Error('请用 node server.js 启动局域网房间服务');}if(!response.ok){if(data.game)accept(data);throw new Error(data.error||'网络请求失败');}return data;}
function accept(data){if(!session||data.code!==session.code||data.revision<session.revision)return;const changed=session.revision!==data.revision;session.revision=data.revision;session.role=data.role||session.role;if(changed){game=data.game;const l=game.lines.find(l=>l.id===selected);index=l?.history.length??0;pending=null;render();}$('roomInfo').textContent=`房间 ${session.code} · 你是${colorName(session.role)}方 · ${data.players?.W?'双方已加入':'等待白方加入'}。让另一设备打开同一电脑的局域网地址，单个空房可直接加入；多房间才需房间码`;
}
async function act(a){if(busy)return;busy=true;try{if(session){const data=await request(`/api/rooms/${session.code}/actions`,{...a,revision:session.revision});accept(data);}else{const id=localAction(a);if(a.type==='play')selected=id;if(a.type==='prune'||!game.lines.some(l=>l.id===selected))selected=game.queue[0]||game.lines[0].id;index=currentLine().history.length;}pending=null;message(a.type==='play'?'已落子。可自由选择本轮尚未操作且轮到自己颜色的时间线':'已更新棋局');return true;}catch(e){message(e.message,true);return false;}finally{busy=false;render();}}
$('confirmMove').onclick=()=>{if(pending!==null)act({type:'play',id:selected,index,at:pending});};$('cancelMove').onclick=()=>{pending=null;render();message('已取消落子预览');};$('pass').onclick=()=>act({type:'play',id:selected,index,at:null});$('history').oninput=e=>{index=Number(e.target.value);pending=null;render();};$('prev').onclick=()=>{index--;pending=null;render();};$('next').onclick=()=>{index++;pending=null;render();};$('live').onclick=()=>{index=currentLine().history.length;pending=null;render();};$('current').onclick=()=>{const choices=E.eligibleIds(game,session?.role).filter(id=>!ai?.isAITurn(id));if(choices.length){selected=choices[0];index=currentLine().history.length;pending=null;render();}else message('暂无你可操作的时间线，请查看黑白棋子标识或等待对方行动');};
for(const c of ['B','W'])$('approve'+c).onclick=()=>act({type:'approveScore',id:selected,color:c});$('resume').onclick=()=>act({type:'resume',id:selected});
$('pruningMode').onchange=updatePruningControls;$('compensationC').onchange=updatePruningControls;$('customC').oninput=updatePruningControls;
$('prune').onclick=()=>{try{const actor=E.replay(currentLine().history,game.size).toPlay,info=E.pruningInfo(game,selected,index,actor);const consequence=info.mode==='resign'?`这些权重将实际判给${colorName(E.other(actor))}方`:`剩余未结算盘的白贴目调整 ${E.weightText(info.komiDelta)} 目，剩余权重按比例归一化`;if(confirm(`剪除这个完整历史子树的 ${info.affectedIds.length} 条叶，原总权重 ${E.weightText(info.subtreeWeight)}？${consequence}。归档路线不可复活。`))act({type:'prune',id:selected,index});}catch(e){message(e.message,true);}};
$('branchLimit').onchange=()=>{$('customLimit').hidden=$('branchLimit').value!=='custom';};
$('new').onclick=()=>{if(game.lines.some(l=>l.history.length)&&!confirm('新对局会替换当前同屏对局，请先导出保存。继续？'))return;try{game=E.createGame(Number($('size').value),Number($('komi').value),chosenLimit(),chosenPruning());selected=1;index=0;pending=null;ai?.reset();render();message('新对局已准备好');}catch(e){message(e.message,true);}};
$('save').onclick=()=>{const blob=new Blob([E.exportGame(game)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='infinite-go.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('load').onchange=async e=>{const f=e.target.files[0];if(!f||session)return;try{if(f.size>10_000_000)throw new Error('导入文件过大（上限 10 MB）');const loaded=E.importGame(await f.text());if(game.lines.some(l=>l.history.length)&&!confirm('导入会替换当前同屏对局。继续？'))return;game=loaded;selected=game.lines[0].id;index=currentLine().history.length;pending=null;ai?.reset();render();message('已导入并验证保存文件');}catch(e){message(e.message,true);}finally{e.target.value='';}};
$('help').onclick=()=>{$('rules').open=true;$('rules').scrollIntoView({behavior:'smooth'});};$('zoomIn').onclick=()=>tree.zoom(1.2);$('zoomOut').onclick=()=>tree.zoom(1/1.2);$('resetTree').onclick=()=>tree.reset();
async function connect(join){if(connecting)return;connecting=true;try{let code=$('roomCode').value.trim().toUpperCase();if(join&&!code){const listing=await request('/api/rooms',undefined,false);const available=listing.rooms.filter(r=>!r.players.W);if(available.length!==1)throw new Error(available.length?'有多个房间，请输入其中一个房间码：'+available.map(r=>r.code).join('、'):'没有可加入的房间，请先在房主设备创建');code=available[0].code;}const data=await request(join?`/api/rooms/${encodeURIComponent(code)}/join`:'/api/rooms',join?{}:{size:Number($('size').value),komi:Number($('komi').value),branchLimitExponent:chosenLimit(),...chosenPruning()},false);session={code:data.code,token:data.token,role:data.role,revision:-1};ai?.reset();try{sessionStorage.setItem('infinite-go-room',JSON.stringify(session));}catch{}selected=1;accept(data);message('已连接局域网房间。房间数据仅保存在主机内存，结束前请导出');}catch(e){message(e.message,true);}finally{connecting=false;}}
$('host').onclick=()=>connect(false);$('join').onclick=()=>connect(true);$('leave').onclick=()=>{session=null;ai?.reset();try{sessionStorage.removeItem('infinite-go-room');}catch{}render();message('已回到同屏模式，保留当前棋局副本');};
setInterval(async()=>{if(!session||busy||polling)return;polling=true;try{accept(await request(`/api/rooms/${session.code}`));if(networkLost){networkLost=false;message('局域网连接已恢复');}}catch(e){networkLost=true;message(`连接中断：${e.message}。正在等待主机恢复，可导出当前副本`,true);}finally{polling=false;}},1500);
if(STATIC_HOST){$('roomInfo').textContent='当前为 GitHub Pages 静态同屏版，不提供房间服务器。局域网 / 虚拟局域网请自行启动 Node 服务，并打开房主地址上的同套页面；不要从本 HTTPS 页面直连 HTTP 局域网后端。';$('connection').textContent='静态同屏版';}
ai=setupAI({staticHost:STATIC_HOST,getGame:()=>game,getSelected:()=>selected,isLAN:()=>!!session,perform:act,onChange:render,message});
$('roomCode').value=new URLSearchParams(location.search).get('room')||'';
render();try{const saved=JSON.parse(sessionStorage.getItem('infinite-go-room'));if(!STATIC_HOST&&saved?.code&&saved?.token){session={...saved,revision:-1};request(`/api/rooms/${session.code}`).then(accept).catch(e=>{session=null;render();message('房间未恢复：'+e.message,true);});}}catch{}
