import {build} from 'esbuild';import {mkdir,copyFile,readFile,writeFile,readdir} from 'node:fs/promises';import {dirname,resolve,join} from 'node:path';import {fileURLToPath} from 'node:url';
const root=dirname(fileURLToPath(import.meta.url)),output=join(root,'dist');await mkdir(join(output,'wasm'),{recursive:true});
const result=await build({absWorkingDir:root,entryPoints:['worker.ts'],outfile:join(output,'engine.worker.js'),bundle:true,minify:true,format:'esm',platform:'browser',target:'es2022',legalComments:'linked',metafile:true});
const wasm=join(root,'node_modules/@tensorflow/tfjs-backend-wasm/dist');for(const file of await readdir(wasm))if(file.endsWith('.wasm'))await copyFile(join(wasm,file),join(output,'wasm',file));
let licenses='Infinite Go browser analysis\nAGPL-3.0-only adapter; source: https://github.com/vavilonska/infinite-go\n\nWeb KatRain upstream MIT license\n'+await readFile(join(root,'UPSTREAM-LICENSE'),'utf8');
const packages=new Set();for(const input of Object.keys(result.metafile.inputs)){const match=input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);if(match)packages.add(match[1]);}
for(const name of [...packages].sort()){const folder=join(root,'node_modules',name);let info;try{info=JSON.parse(await readFile(join(folder,'package.json'),'utf8'));}catch{continue;}licenses+='\n\n'+name+' '+info.version+' '+String(info.license||'')+'\n';for(const file of await readdir(folder))if(/^(LICENSE|LICENCE|COPYING|NOTICE)(\.|$)/i.test(file))try{licenses+=await readFile(join(folder,file),'utf8')+'\n';}catch{}}
await writeFile(join(output,'THIRD-PARTY-LICENSES.txt'),licenses);console.log('Built optional browser worker and WASM assets; neural-network weights are not bundled.');
const {stat}=await import('node:fs/promises');const {createHash}=await import('node:crypto');const sizes=[];for(const name of await readdir(output)){if(name==='runtime-info.json'||name==='wasm')continue;sizes.push({path:name,bytes:(await stat(join(output,name))).size,sha256:createHash('sha256').update(await readFile(join(output,name))).digest('hex')});}for(const name of await readdir(join(output,'wasm')))sizes.push({path:'wasm/'+name,bytes:(await stat(join(output,'wasm',name))).size,sha256:createHash('sha256').update(await readFile(join(output,'wasm',name))).digest('hex')});await writeFile(join(output,'runtime-info.json'),JSON.stringify({bytes:sizes.reduce((n,f)=>n+f.bytes,0),files:sizes}));
